version: "3"
networks:
  default:
    external:
      name: workwithvpn
services:
  argvmatey-spotify:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: argvmatey-spotify
    image: argvmatey-spotify
    environment:
      - DEVICE_NAME='CHANGEME'
      - PASSWORD='CHANGEME'
      - USERNAME='CHANGEME'
    # mount your hard drive here
    volumes:
      - ./volume:/volume
